In [9]:
import os
print(os.getcwd())

/Users/rohiththota/Local-Repo/complete-guide-to-analytics-engineering

In [11]:
import pandas as pd

df = pd.read_csv("/Users/rohiththota/Local-Repo/complete-guide-to-analytics-engineering/red_30_tech_us_sales.csv")
print(df.head())

      EmpID   OrderNum  OrderDate  OrderType  Quantity     Price   Discount   \
0  900015476   1100948   9/3/2017     Retail         1    $44.95          0
1  900015476   1101096  9/24/2017  Wholesale        10     $4.99      $1.00
2  900015476   1101138  10/1/2017  Wholesale         4   $250.00     $50.00
3  900015476   1101158  10/3/2017     Retail         1   $250.00          0
4  900015476   1101181  10/9/2017     Retail         1    $13.99          0

   Order Total
0       $44.95
1       $48.90
2      $950.00
3      $250.00
4       $13.99

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4976 entries, 0 to 4975
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EmpID          4976 non-null   int64
 1   OrderNum       4976 non-null   int64
 2   OrderDate      4976 non-null   object
 3   OrderType      4976 non-null   object
 4   Quantity       4976 non-null   int64
 5    Price         4976 non-null   object
 6    Discount      4976 non-null   object
 7    Order Total   4976 non-null   object
dtypes: int64(3), object(5)
memory usage: 311.1+ KB

In [21]:
df[df['Quantity'] > 100]

,EmpID,OrderNum,OrderDate,OrderType,Quantity,Price,Discount,Order Total
68,900015476,1105783,8/11/2019,Wholesale,101,$10.99,$2.20,"$1,107.79"
246,900018190,1102345,3/28/2018,Wholesale,109,$189.00,$37.80,"$20,563.20"
370,900018190,1105374,6/9/2019,Wholesale,104,$23.99,$4.80,"$2,490.16"
382,900018190,1105688,7/27/2019,Wholesale,106,$49.00,$9.80,"$5,184.20"
395,900010405,1101134,9/30/2017,Wholesale,102,$9.99,$2.00,"$1,016.98"
559,900014598,1101150,10/2/2017,Wholesale,109,$29.99,$6.00,"$3,262.91"
570,900014598,1101579,12/3/2017,Wholesale,103,$8.99,$1.80,$924.17
573,900014598,1101619,12/8/2017,Wholesale,107,$19.50,$3.90,"$2,082.60"
590,900014598,1102127,2/24/2018,Wholesale,103,$119.00,$23.80,"$12,233.20"
614,900014598,1102972,6/26/2018,Wholesale,102,$15.50,$3.10,"$1,577.90"
670,900014598,1104791,3/15/2019,Wholesale,102,$12.00,$2.40,"$1,221.60"
709,900014032,1101001,9/11/2017,Wholesale,104,$179.00,$35.80,"$18,580.20"
890,900012972,1101198,10/11/2017,Wholesale,104,$12.00,$2.40,"$1,245.60"
1135,900019833,1102082,2/16/2018,Retail,109,$23.99,0,"$2,614.91"
1161,900019833,1103013,7/1/2018,Wholesale,106,$11.99,$2.40,"$1,268.54"
1245,900014980,1102307,3/21/2018,Wholesale,104,$450.00,$90.00,"$46,710.00"
1560,900016416,1102019,2/6/2018,Wholesale,102,$34.99,$7.00,"$3,561.98"
1621,900016416,1103863,10/28/2018,Wholesale,103,$24.95,$4.99,"$2,564.86"
1741,900012326,1102670,5/14/2018,Wholesale,109,$49.95,$9.99,"$5,434.56"
1821,900012326,1105716,7/31/2019,Wholesale,109,$19.50,$3.90,"$2,121.60"
1844,900012483,1102001,2/4/2018,Wholesale,107,$250.00,$50.00,"$26,700.00"
1854,900012483,1102510,4/21/2018,Wholesale,108,$13.99,$2.80,"$1,508.12"
1985,900010875,1103871,10/29/2018,Wholesale,101,$189.00,$37.80,"$19,051.20"
2121,900010836,1104280,12/27/2018,Retail,108,$49.00,0,"$5,292.00"
2126,900010836,1104729,3/7/2019,Wholesale,104,$13.99,$2.80,"$1,452.16"
2310,900018661,1105107,5/1/2019,Wholesale,106,$8.99,$1.80,$951.14
2922,900015938,1101823,1/7/2018,Wholesale,104,$37.99,$7.60,"$3,943.36"
2944,900015938,1102278,3/16/2018,Wholesale,102,$36.99,$7.40,"$3,765.58"
3015,900015938,1104132,12/9/2018,Wholesale,105,$49.00,$9.80,"$5,135.20"
3021,900015938,1104177,12/15/2018,Wholesale,109,$54.00,$10.80,"$5,875.20"
3069,900015938,1105209,5/18/2019,Wholesale,103,$58.95,$11.79,"$6,060.06"
3127,900010430,1102320,3/23/2018,Wholesale,105,$42.99,$8.60,"$4,505.35"
3177,900010430,1104193,12/17/2018,Wholesale,107,$54.00,$10.80,"$5,767.20"
3191,900010430,1104741,3/9/2019,Wholesale,108,$4.99,$1.00,$537.92
3258,900016297,1102242,3/11/2018,Wholesale,101,$29.99,$6.00,"$3,022.99"
3293,900016297,1103447,8/26/2018,Wholesale,104,$499.00,$99.80,"$51,796.20"
3363,900015082,1101118,9/27/2017,Wholesale,103,$8.99,$1.80,$924.17
3394,900015082,1102039,2/9/2018,Wholesale,104,$36.99,$7.40,"$3,839.56"
3525,900015082,1105875,8/24/2019,Wholesale,103,$245.00,$49.00,"$25,186.00"
3602,900016088,1101632,12/10/2017,Wholesale,106,$8.99,$1.80,$951.14
3795,900013626,1102954,6/23/2018,Wholesale,102,$37.99,$7.60,"$3,867.38"
3884,900013626,1104786,3/14/2019,Wholesale,102,$395.00,$79.00,"$40,211.00"
3977,900013387,1102112,2/22/2018,Wholesale,101,$250.00,$50.00,"$25,200.00"
4265,900015673,1104335,1/3/2019,Wholesale,104,$24.95,$4.99,"$2,589.81"
4267,900015673,1104444,1/23/2019,Wholesale,104,$23.99,$4.80,"$2,490.16"
4297,900011056,1101620,12/8/2017,Wholesale,103,$8.99,$1.80,$924.17
4448,900013587,1101423,11/9/2017,Wholesale,103,$10.99,$2.20,"$1,129.77"
4567,900016602,1103188,7/23/2018,Wholesale,106,$24.99,$5.00,"$2,643.94"
4568,900016602,1103212,7/26/2018,Wholesale,103,$119.00,$23.80,"$12,233.20"
4686,900011678,1103754,10/12/2018,Wholesale,105,$29.99,$6.00,"$3,142.95"
4696,900011678,1104351,1/6/2019,Wholesale,103,$684.00,$136.80,"$70,315.20"
4703,900011678,1104708,3/3/2019,Wholesale,102,$189.00,$37.80,"$19,240.20"
4769,900018460,1102559,4/29/2018,Wholesale,102,$29.99,$6.00,"$3,052.98"
4928,900011189,1102015,2/6/2018,Wholesale,101,$34.99,$7.00,"$3,526.99"

In [14]:
df[(df['Quantity'] > 100) & (df['OrderType'] == 'Retail')]

,EmpID,OrderNum,OrderDate,OrderType,Quantity,Price,Discount,Order Total
1135,900019833,1102082,2/16/2018,Retail,109,$23.99,0,"$2,614.91"
2121,900010836,1104280,12/27/2018,Retail,108,$49.00,0,"$5,292.00"

In [31]:
df['Quantity'].describe()

count    4976.000000
mean       11.107516
std        20.367634
min         1.000000
25%         1.000000
50%         5.000000
75%        10.000000
max       109.000000
Name: Quantity, dtype: float64

In [32]:
unique_ids=pd.Series(df['EmpID '].unique())
print(unique_ids)

0     900015476
1     900019884
2     900012297
3     900018190
4     900010405
5     900014598
6     900014032
7     900012180
8     900012972
9     900012260
10    900019833
11    900014980
12    900013598
13    900018996
14    900016416
15    900012326
16    900012483
17    900010875
18    900010836
19    900018661
20    900012723
21    900019311
22    900018689
23    900019978
24    900015938
25    900010430
26    900016297
27    900015082
28    900017930
29    900016088
30    900013626
31    900013387
32    900017044
33    900012258
34    900015673
35    900011056
36    900019250
37    900016392
38    900013587
39    900016602
40    900011678
41    900018460
42    900010813
43    900011189
dtype: int64